name: Build EXE 2026

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # 升级到 v4，解决 Node.js 警告

    - name: Set up Python
      uses: actions/setup-python@v5 # 升级到 v5，解决 Node.js 警告
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE with PyInstaller
      shell: pwsh
      run: |
        # 自动检测当前文件夹下到底哪个才是主程序
        $mainFile = if (Test-Path "wowfish.py") { "wowfish.py" } else { "main.py" }
        Write-Host "检测到主程序为: $mainFile"
        pyinstaller --onefile --name "WowFish_Tool" $mainFile

    - name: Upload Artifact
      uses: actions/upload-artifact@v4 # 必须使用 v4
      with:
        name: WowFish-Windows-EXE
        path: dist/WowFish_Tool.exe
