name: Build EXE

on:
  workflow_dispatch: # 允许手动点击运行

jobs:
  build:
    runs-on: windows-latest # 在微软的 Windows 服务器上运行

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE with PyInstaller
      run: |
        pyinstaller --onefile --name "WowFish_Tool" main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4  # 这里从 v3 改成 v4
      with:
        name: WowFish-Windows-EXE
        path: dist/WowFish_Tool.exe
